### ISSUE TITLE
용어 설명 좀 해주세요.

### ISSUE THREAD

**Issue by wiznet-mason** [bangbh81/winc_document#1]
Device twin, Desired property, Reported property에 대한 설명 필요

Topic 간에 표로 설명 필요 (아래 예시)
|Topic Name|PUB / SUB|Description|
|------|---|---|
|$iothub/twin/PATCH/properties/desired/#|SUB|Device Information Pub Topic|
|iothub/twin/PATCH/properties/reported/?rid={requeste id}|SUB|F/W Information, User Data Sub Topic|
|devices/{devices name}/message/events/|PUB|User Data Pub Topic|

**Comment by bangbh81** [comment]
요렇게?
![image](https://user-images.githubusercontent.com/11305037/93844582-97e93500-fcd8-11ea-8e96-ec36831c4375.png)

**Comment by wiznet-mason** [comment]
넹 좋네요

**Comment by bangbh81** [comment]
Mqtt topic table is added on the top
